export const actionTypes = {
  // Component actions
  LOAD_COMPONENT: 'shared/LOAD_COMPONENT',
  COMPONENT_NOT_FOUND: 'shared/COMPONENT_NOT_FOUND',
  UNLOAD_COMPONENT: 'shared/UNLOAD_COMPONENT',

  LOAD_COMPONENT_SUCCESS: 'shared/LOAD_COMPONENT_SUCCESS',
  LOAD_COMPONENT_ERROR: 'shared/LOAD_COMPONENT_ERROR',
  LOAD_COMPONENT_FAILED: 'shared/LOAD_COMPONENT_FAILED',

  // Shared API Requests
  API_REQUEST_ERROR: 'shared/API_REQUEST_ERROR',
  API_REQUEST_UNAUTHORIZED: 'shared/API_REQUEST_UNAUTHORIZED',
  API_REQUEST_NOT_FOUND: 'shared/API_REQUEST_NOT_FOUND',

  API_REQUEST: 'shared/API_REQUEST',
  API_REQUEST_DONE: 'shared/API_REQUEST_DONE',

  API_TEST_ACTION: 'shared/API_TEST_ACTION',

  //Shared Alert
  SET_ALERT: 'shared/SET_ALERT',
  CLEAR_ALERT: 'shared/CLEAR_ALERT',

  // Shared Confirmation
  OPEN_CONFIRMATION_MODAL: 'shared/OPEN_CONFIRMATION_MODAL',
  CLOSE_CONFIRMATION_MODAL: 'shared/CLOSE_CONFIRMATION_MODAL',
  CONFIRM_CONFIRMATION_MODAL: 'shared/CONFIRM_CONFIRMATION_MODAL',
  REJECT_CONFIRMATION_MODAL: 'shared/REJECT_CONFIRMATION_MODAL',

  // Site Components - Invalid Route Component Actions
  INVALID_ROUTE_COMPONENT: 'site/shared/INVALID_ROUTE_COMPONENT',

  // Site Components - Auth Component Actions
  AUTH_COMPONENT: 'site/auth/AUTH_COMPONENT',
  LOGIN: 'site/auth/LOGIN',
  LOGOUT: 'site/auth/LOGOUT',
  CLEAR_USER_DATA: 'site/auth/CLEAR_USER_DATA',

  // Site Components - Invalid Route Component Actions
  LOAD_HOME_COMPONENT: 'site/home/LOAD_HOME_COMPONENT',
  LOAD_HOME_COMPONENT_SUCCESS: 'site/home/LOAD_HOME_COMPONENT_SUCCESS',
  LOAD_HOME_COMPONENT_FAILED: 'site/home/LOAD_HOME_COMPONENT_FAILED',

  UNLOAD_HOME_COMPONENT: 'site/home/UNLOAD_HOME_COMPONENT',
  UNLOAD_HOME_COMPONENT_SUCCESS: 'site/home/UNLOAD_HOME_COMPONENT_SUCCESS',
  UNLOAD_HOME_COMPONENT_FAILED: 'site/home/UNLOAD_HOME_COMPONENT_FAILED',

  HOME_COMPONENT: 'site/home/HOME_COMPONENT',
  GET_RESERVATIONS: 'site/home/GET_RESERVATIONS',

  // Site Components - Reservations Actions
  RESERVATIONS_COMPONENT: 'site/reservations/RESERVATIONS_COMPONENT',

  LOAD_NEW_RESERVATION_COMPONENT:
    'site/reservations/LOAD_NEW_RESERVATION_COMPONENT',
  LOAD_NEW_RESERVATION_COMPONENT_SUCCESS:
    'site/reservations/LOAD_NEW_RESERVATION_COMPONENT_SUCCESS',
  LOAD_NEW_RESERVATION_COMPONENT_FAILED:
    'site/reservations/LOAD_NEW_RESERVATION_COMPONENT_FAILED',

  UNLOAD_NEW_RESERVATION_COMPONENT:
    'site/reservations/UNLOAD_NEW_RESERVATION_COMPONENT',
  UNLOAD_NEW_RESERVATION_COMPONENT_SUCCESS:
    'site/reservations/UNLOAD_NEW_RESERVATION_COMPONENT_SUCCESS',
  UNLOAD_NEW_RESERVATION_COMPONENT_FAILED:
    'site/reservations/UNLOAD_NEW_RESERVATION_COMPONENT_FAILED',

  NEW_RESERVATION_COMPONENT: 'site/reservations/NEW_RESERVATION_COMPONENT',
  GET_ROOM_IDS: 'site/reservations/GET_ROOM_IDS',

  CREATE_RESERVATION: 'site/reservations/create/CREATE_RESERVATION',
  CREATE_RESERVATION_SUCCESS:
    'site/reservations/create/CREATE_RESERVATION_SUCCESS',
  CREATE_RESERVATION_FAILED:
    'site/reservations/create/CREATE_RESERVATION_FAILED',

  DELETE_RESERVATION: 'site/reservations/delete/DELETE_RESERVATION',
  DELETE_RESERVATION_SUCCESS:
    'site/reservations/delete/DELETE_RESERVATION_SUCCESS',
  DELETE_RESERVATION_FAILED:
    'site/reservations/delete/DELETE_RESERVATION_FAILED',

  LOAD_EDIT_RESERVATION_COMPONENT:
    'site/reservations/edit/LOAD_EDIT_RESERVATION_COMPONENT',
  LOAD_EDIT_RESERVATION_COMPONENT_SUCCESS:
    'site/reservations/edit/LOAD_EDIT_RESERVATION_COMPONENT_SUCCESS',
  LOAD_EDIT_RESERVATION_COMPONENT_FAILED:
    'site/reservations/edit/LOAD_EDIT_RESERVATION_COMPONENT_FAILED',

  UNLOAD_EDIT_RESERVATION_COMPONENT:
    'site/reservations/edit/UNLOAD_EDIT_RESERVATION_COMPONENT',
  UNLOAD_EDIT_RESERVATION_COMPONENT_SUCCESS:
    'site/reservations/edit/UNLOAD_EDIT_RESERVATION_COMPONENT_SUCCESS',
  UNLOAD_EDIT_RESERVATION_COMPONENT_FAILED:
    'site/reservations/edit/UNLOAD_EDIT_RESERVATION_COMPONENT_FAILED',

  EDIT_RESERVATION_COMPONENT: 'site/reservations/update/NEW_RESERVATION',

  UPDATE_RESERVATION: 'site/reservations/update/CREATE_RESERVATION',
  UPDATE_RESERVATION_SUCCESS:
    'site/reservations/update/CREATE_RESERVATION_SUCCESS',
  UPDATE_RESERVATION_FAILED:
    'site/reservations/update/CREATE_RESERVATION_FAILED',

  LOAD_SHOW_RESERVATION_COMPONENT:
    'site/reservations/show/LOAD_SHOW_RESERVATION_COMPONENT',
  LOAD_SHOW_RESERVATION_COMPONENT_SUCCESS:
    'site/reservations/show/LOAD_SHOW_RESERVATION_COMPONENT_SUCCESS',
  LOAD_SHOW_RESERVATION_COMPONENT_FAILED:
    'site/reservations/show/LOAD_SHOW_RESERVATION_COMPONENT_FAILED',

  UNLOAD_SHOW_RESERVATION_COMPONENT:
    'site/reservations/show/UNLOAD_SHOW_RESERVATION_COMPONENT',
  UNLOAD_SHOW_RESERVATION_COMPONENT_SUCCESS:
    'site/reservations/show/UNLOAD_SHOW_RESERVATION_COMPONENT_SUCCESS',
  UNLOAD_SHOW_RESERVATION_COMPONENT_FAILED:
    'site/reservations/show/UNLOAD_SHOW_RESERVATION_COMPONENT_FAILED',

  SHOW_RESERVATION_COMPONENT: 'site/reservations/show/RESERVATION',
  GET_RESERVATION: 'site/reservations/show/GET_RESERVATION',

  // Site Components - Dashboard Actions
  DASHBOARD_COMPONENT: 'site/dashboard/DASHBOARD_COMPONENT',
  GET_DASHBOARD_DATA: 'site/dashboard/GET_DASHBOARD_DATA',
};
